### ISSUE TITLE
ecommerce

### ISSUE THREAD

**Issue by tejasai0** [codewithzosh/ecommerce-products-data#1]
i am unable to login  it showing a network  error plz help me

**Comment by Joshwa034** [comment]
please provide the filter data(filterdata.js) as it is missing ecom data files.

**Comment by ashishnxt** [comment]
can you give me the source code. i can try to fix it for you

**Comment by tonnymuchui** [comment]
anyone with final project navigation component page?

**Comment by gracious7** [comment]
can you give me the source code i'm messed up with some files

**Comment by ashishnxt** [comment]
[Uploading ecommerce-mern.zip…]()
